name: Build & Deploy
on: [push]

env:
  SCRVER: ${{ github.sha }}

jobs:
  server:
    name: Build Server
    runs-on: ubuntu-latest

    env:
      GO111MODULE: "on"
      CGO_ENABLED: 0
      GOPATH: ""
      GOBIN: ""

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install Golang
        uses: actions/setup-go@v1
        with:
          go-version: "1.13.x"

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Export bin paths
        run: |
          export GOPATH=$(go env GOPATH)
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOBIN
          mkdir -p $GOBIN

      - name: Install PostCSS CLI
        run: npm i -g postcss-cli

      - name: Install Golang Dep
        run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: Install Packr2
        run: go get -u -v github.com/gobuffalo/packr/v2/packr2

      - name: Print ls
        run: |
          echo $GOPATH
          echo $GOBIN

      - name: Print bin ls
        run: |
          ls -la $GOPATH/bin
          ls -la $GOBIN

      - name: Install UPX
        run: |
          wget https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz
          tar -xf upx-3.95-amd64_linux.tar.xz
          mv upx-3.95-amd64_linux/upx $GITHUB_WORKSPACE/upx
      
      - name: Process UI
        working-directory: server/ui/template
        run: |
          yarn
          postcss styles.css -o dist/styles.css
          cp index.html dist/index.html

      - name: Install server dependencies
        working-directory: server
        run: go get -u

      - name: Pack UI files
        working-directory: server
        run: packr2

      - name: Build Windows binary
        working-directory: server
        run: go build -ldflags "-s -w -X github.com/rumblefrog/source-chat-relay/server/config.SCRVER=$SCRVER -extldflags '-static'" -o server

  client:
    name: Build Client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sm-version: ["1.10", "1.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install sourcemod
        run: |
          SMLATEST=`curl -s "https://www.sourcemod.net/smdrop/${{ matrix.sm-version }}/sourcemod-latest-linux"`
          SMPACKAGE="https://www.sourcemod.net/smdrop/${{ matrix.sm-version }}/$SMLATEST"
          wget $SMPACKAGE
          tar -xzf $(basename "$SMPACKAGE")

      - name: Update version file
        working-directory: client
        run: envsubst < SCR-Version.inc > SCR-Version.inc.temp && mv SCR-Version.inc.temp SCR-Version.inc

      - name: Move source to scripting
        run: cp -r client/* addons/sourcemod/scripting/

      - name: Fetch plugin dependencies
        run: |
          wget https://raw.githubusercontent.com/nefarius/sm-ext-socket/master/socket.inc -P addons/sourcemod/scripting/include/
          wget https://raw.githubusercontent.com/rumblefrog/SM-ByteBuffer-Inc/master/bytebuffer.inc -P addons/sourcemod/scripting/include/
          wget https://www.doctormckay.com/download/scripting/include/morecolors.inc -P addons/sourcemod/scripting/include/

      - name: Permission adjustment
        working-directory: addons/sourcemod/scripting/
        run: chmod +x spcomp

      - name: Build client
        working-directory: addons/sourcemod/scripting/
        run: ./spcomp Source-Chat-Relay.sp
  doc:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Export npm bin path
        run: export PATH=$PATH:$(npm bin -g)

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        working-directory: docs
        run: yarn

      - name: Build documentation
        working-directory: docs
        run: yarn gatsby build --prefix-paths
