name: Build & Deploy
on: [push]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.13"]

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Use go ${{ matrix.go-version }}
      uses: cedrickring/golang-action${{ matrix.go-version }}@1.4.1
      env:
        GO111MODULE: "on"
        PROJECT_PATH: "./server"
      with:
        args: go build
