name: Build & Deploy
on: [push]

jobs:
  server:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Compile server bin
        uses: cedrickring/golang-action$@1.4.1
        env:
          GO111MODULE: "on"
          PROJECT_PATH: "./server"
        with:
          args: go build
  client:
    name: Build Client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sm-version: ["1.9", "1.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install sourcemod
        run: |
          SMLATEST=`curl -s "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
          SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
          wget $SMPACKAGE
          tar -xzf $(basename "$SMPACKAGE")

      - name: Move source to scripting
        run: |
          cp -r client/* addons/sourcemod/scripting/

      - name: Fetch plugin dependencies
        run: |
          wget https://raw.githubusercontent.com/nefarius/sm-ext-socket/master/socket.inc -P addons/sourcemod/scripting/include/
          wget https://raw.githubusercontent.com/rumblefrog/SM-ByteBuffer-Inc/master/bytebuffer.inc -P addons/sourcemod/scripting/include/
          https://www.doctormckay.com/download/scripting/include/morecolors.inc -P addons/sourcemod/scripting/include/

      - name: Permission adjustment
        run: |
          chmod +x addons/sourcemod/scripting/spcomp

      - name: Navigate to scripting
        run: |
          cd addons/sourcemod/scripting/

      - name: Build client
        run: |
          ./spcomp Source-Chat-Relay.sp
