name: Build & Deploy
on: [push]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.12' ]

    steps:
    - uses: actions/checkout@master
    
    - name: Use go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        version: ${{ matrix.go-version }}

    - name: Install server dependencies
      run: go get -v -t -d -u ./server

    - name: Build server
      run: go build ./server
